from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def one(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "1")
    def two(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "2")
    def three(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "3")
    def four(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "4")
    def five(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "5")
    def six(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "6")
    def seven(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "7")
    def eight(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "8")
    def nine(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "9")
    def add_text(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "+")
    def subtract_text(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "-")
    def multiply_text(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "X")
    def divide_text(self):
        text = self.textBrowser.toPlainText()
        self.textBrowser.setText(text + "÷")
    def calculate(self):
        text = self.textBrowser.toPlainText()
        equation = eval(text)
        result = str(equation)
        self.textBrowser.setText(result)
    def clear(self):
        self.textBrowser.setText("")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 240, 101, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.one)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 240, 101, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.two)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 240, 101, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.three)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 420, 101, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.seven)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 330, 101, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.six)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 330, 101, 81))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.five)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 330, 101, 81))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.four)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 420, 101, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.eight)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 420, 101, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.nine)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(350, 190, 81, 61))
        self.add.setObjectName("add")
        self.add.clicked.connect(self.add_text)
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(350, 310, 81, 61))
        self.multiply.setObjectName("multiply")
        self.multiply.clicked.connect(self.multiply_text)
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(350, 250, 81, 61))
        self.subtract.setObjectName("subtract")
        self.subtract.clicked.connect(self.subtract_text)
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(350, 370, 81, 61))
        self.divide.setObjectName("divide")
        self.divide.clicked.connect(self.divide_text)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(350, 430, 81, 61))
        self.equal.setObjectName("equal")
        self.equal.clicked.connect(self.calculate)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 90, 421, 91))
        self.textBrowser.setObjectName("textBrowser")
        font1 = QtGui.QFont()
        font1.setPointSize(14)
        self.textBrowser.setFont(font1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QtCore.QRect(10, 200, 71, 31))
        self.pushButton_10.clicked.connect(self.clear)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AryaSoft Calculator"))
        self.label.setText(_translate("MainWindow", "Calculator"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "7"))
        self.pushButton_5.setText(_translate("MainWindow", "6"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "4"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.add.setText(_translate("MainWindow", "+"))
        self.multiply.setText(_translate("MainWindow", "X"))
        self.subtract.setText(_translate("MainWindow", "-"))
        self.divide.setText(_translate("MainWindow", "÷"))
        self.equal.setText(_translate("MainWindow", "="))
        self.pushButton_10.setText(QtCore.QCoreApplication.translate("MainWindow", u"Clear", None))


if __name__ == "__main__":
    import qdarkstyle
    import darkdetect
    if darkdetect.isDark() == True:
        import sys
        app = QtWidgets.QApplication(sys.argv)
        app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
    if darkdetect.isLight() == True:
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())